export enum Icons {
  logo = 'logo',
  person= 'person',
  create= 'create',
  emoji_events= 'emoji_events',
  search= 'search',
  facebook = 'facebook',
  github = 'github',
  linkedin = 'linkedin',
  skype = 'skype',
  twitter = 'twitter',
  medium = 'medium',
  arrow_drop_down = 'arrow_drop_down',
  home = 'home',
  sign_out = 'sign_out',
  account_circle = 'account_circle',
  close = 'close',
  info = 'info',
  question = 'question',
  list = 'list',
  pen_square = 'pen_square',
  folder_closed_solid = 'folder_closed_solid',
  check_solid = 'check_solid',
  comments_solid = 'comments_solid',
  calendar_solid = 'calendar_solid',
  eye_solid = 'eye_solid',
  star_solid = 'star_solid',
  comment_solid = 'comment_solid',
  asterisk_solid = 'asterisk_solid'

}